import { StyleSheet } from 'react-native';
import {
  Green,
  MineShaft,
  White,
  GullGray,
  AquaHaze,
  DodgerBlue,
  Midnight,
  Monza,
  Scorpion,
  PattensBlue,
  WoodSmoke,
  Tundora,
  ForgetMeNot,
} from '../../../components';
import { circle, hp, wp } from '../../../components/utils';

export const home = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: 'center',
  },
  headerGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp(331),
    marginTop: hp(13),
  },
  profileImage: circle(46),
  usernameView: {
    marginLeft: wp(11),
  },
  fullname: {
    fontSize: 20,
    color: MineShaft,
  },
  username: {
    fontSize: 14,
    color: Scorpion,
  },
  bell: {
    width: wp(42),
    height: hp(41),
    borderRadius: 10,
    backgroundColor: Green,
    alignItems: 'center',
    justifyContent: 'center',
    right: wp(18),
    position: 'absolute',
  },

  mainView: {
    // flex: 1,
    marginTop: hp(87),
    height: hp(680),
    position: 'relative',
    // bottom: 0,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    elevation: 5,
    backgroundColor: White,
    width: '100%',
    zIndex: 40,
    alignItems: 'center',
  },
  billContainer: {
    height: hp(374),
    width: wp(339),
    backgroundColor: White,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    borderRadius: 25,
    marginTop: hp(15),
  },
  billWrapper: {
    width: wp(332),
    height: hp(364),
    backgroundColor: PattensBlue,
    borderRadius: 25,
    position: 'relative',
  },
  billsBgContainer: {
    position: 'absolute',
    bottom: 0,
  },
  billsBg: {
    width: wp(353),
    height: hp(478),
  },
  heartHandWrapper: {
    width: wp(292),
    height: hp(127),
    borderRadius: 20,
    backgroundColor: White,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(20),
  },
  heartHandContainer: {
    width: wp(276),
    height: hp(113),
    borderRadius: 20,
    backgroundColor: DodgerBlue,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  handHeart: {
    width: wp(203),
    height: hp(128),
    marginTop: hp(16),
  },

  billsLeadText: {
    fontSize: 20,
    color: WoodSmoke,
    marginLeft: wp(51),
    marginTop: hp(25),
  },
  billsText: {
    fontSize: 15,
    color: Tundora,
    marginLeft: wp(51),
    width: wp(243),
    lineHeight: 21,
  },
  billsButton: {
    backgroundColor: DodgerBlue,
    width: wp(201),
    marginTop: hp(29),
    marginLeft: wp(51),
  },

  bottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: wp(339),
  },
  miniContainer: {
    height: hp(192),
    width: wp(162),
    backgroundColor: White,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    borderRadius: 25,
    marginTop: hp(15),
  },
  miniWrapper: {
    width: wp(156),
    height: hp(182),
    backgroundColor: ForgetMeNot,
    borderRadius: 25,
    position: 'relative',
  },
  minisBgContainer: {
    position: 'absolute',
    bottom: 0,
  },
  minisBg: {
    // width: wp(313), // wp(127),
    // height: hp(252), // hp(56),
    width: wp(156),
    height: hp(181),
  },
  miniImageWrapper: {
    width: wp(131),
    height: hp(64),
    borderRadius: 10,
    backgroundColor: White,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(20),
  },
  miniImageContainer: {
    borderRadius: 10,
  },
  miniImage: {
    width: wp(127),
    height: hp(56),
  },

  miniLeadText: {
    fontSize: 15,
    color: WoodSmoke,
    marginLeft: wp(33),
    marginTop: hp(11),
    lineHeight: 17,
  },

  arrowView: {
    marginLeft: wp(32),
    marginTop: hp(21),
  },
});

export const homeEX = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: 'center',
    height: '100%', // hdp(758),
    width: '100%', // wdp(375),
    backgroundColor: Green,
  },
  imageBg: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    bottom: 0,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(26),
    width: wp(323),
    justifyContent: 'space-between',
  },
  userImage: {
    width: wp(46),
    height: wp(46),
    borderRadius: wp(46) / 2,
  },
  menuView: {
    width: wp(40),
    height: wp(40),
    borderRadius: wp(40) / 2,
    backgroundColor: White,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeText: {
    fontSize: 25,
    alignSelf: 'flex-start',
    color: '#F5F5F5',
    marginTop: hp(21),
    marginLeft: wp(22),
  },
  username: {
    fontSize: 25,
    alignSelf: 'flex-start',
    color: White,
    marginLeft: wp(32),
  },
  mainCard: {
    width: wp(344),
    height: hp(444),
    borderRadius: 14,
    backgroundColor: '#F2F2F2',
    marginTop: hp(14),
  },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileGroup: {
    width: wp(79),
    height: hp(35),
    // marginTop: hp(13),
  },
  imageRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileView: {
    width: wp(182),
    height: hp(81),
    borderRadius: 14,
    backgroundColor: White,
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletView: {
    width: wp(155),
    height: hp(81),
    borderRadius: 14,
    backgroundColor: White,
    justifyContent: 'center',
  },
  title: {
    lineHeight: 19,
    fontSize: 11,
    color: MineShaft,
    marginLeft: wp(7),
    // marginTop: hp(13),
  },
  walletTitle: {
    lineHeight: 19,
    fontSize: 11,
    color: MineShaft,
    marginLeft: wp(21),
    // marginTop: hp(13),
  },
  amount: {
    fontSize: 16,
    color: Green,
    // marginTop: hp(5),
    marginLeft: wp(21),
  },
  availableText: {
    fontSize: 10,
    color: GullGray,
    marginLeft: wp(21),
  },

  billsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: wp(278),
    alignSelf: 'center',
    marginTop: hp(35),
  },
  leadBills: {
    fontSize: 16,
    color: MineShaft,
  },
  seeAll: {
    fontSize: 13,
    color: Green,
  },

  rentCard: {
    width: wp(286),
    height: hp(55),
    borderRadius: 9,
    backgroundColor: Green,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(20),
  },
  cardBadge: {
    width: wp(35.8),
    height: wp(35.8),
    borderRadius: wp(35.8) / 2,
    backgroundColor: '#00b383',
    justifyContent: 'center',
    alignItems: 'center',
  },
  note: {
    width: wp(14),
    height: hp(18),
  },
  cardMainGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: wp(266),
    alignSelf: 'center',
    // marginTop: hp(35),
  },
  cardGrid: {
    // flexDirection: 'row',
    // alignItems: 'center',
    // justifyContent: 'space-between',
    width: wp(218),
    // alignSelf: 'center',
    // marginTop: hp(35),
  },
  innerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  billTitle: {
    fontSize: 11,
    color: White,
  },
  billAmountTitle: {
    fontSize: 11,
    color: White,
  },
  billStatus: {
    fontSize: 11,
    color: White,
  },
  billAmount: {
    fontSize: 12,
    color: White,
  },

  electricityCard: {
    width: wp(286),
    height: hp(55),
    borderRadius: 9,
    backgroundColor: White,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(20),
    borderWidth: 1,
    borderColor: DodgerBlue,
  },
  flash: {
    width: wp(14.7),
    height: hp(20),
  },
  lightCardBadge: {
    width: wp(35.8),
    height: wp(35.8),
    borderRadius: wp(35.8) / 2,
    backgroundColor: AquaHaze,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lightBillTitle: {
    fontSize: 11,
    color: Midnight,
  },
  lightBillAmountTitle: {
    fontSize: 11,
    color: GullGray,
  },
  lightBillStatus: {
    fontSize: 11,
    color: GullGray,
  },
  lightBillAmount: {
    fontSize: 12,
    color: Green,
  },

  netflixCard: {
    width: wp(286),
    height: hp(55),
    borderRadius: 9,
    backgroundColor: White,
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: hp(20),
    borderWidth: 1,
    borderColor: Monza,
  },
  button: {
    marginTop: hp(15),
    width: wp(204),
    height: hp(48),
    backgroundColor: '#ccfff1',
    borderColor: Green,
    borderWidth: 1,
    borderRadius: 12,
    alignSelf: 'center',
  },
  buttonTitle: {
    color: Green,
  },
});
